busbarn/urls.py
from django.conf.urls import url

from . import views

app_name = 'vehicles'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    
    url(r'^vehicle/add/$', views.vehicle_add, name='vehicle_add'),
    url(r'^vehicle/$', views.vehicle_list, name='vehicle_list'),
    url(r'^vehicle/(?P<vehicle_id>[0-9]+)/$', views.vehicle_detail, name='vehicle_detail'),
    url(r'^vehicle/(?P<vehicle_id>[0-9]+)/edit/$', views.vehicle_edit, name='vehicle_edit'),
    
    url(r'^mechanic/add/$', views.mechanic_add, name='mechanic_add'),
    url(r'^mechanic/$', views.mechanic_list, name='mechanic_list'),
    url(r'^mechanic/(?P<mechanic_id>[0-9]+)/edit/$', views.mechanic_edit, name='mechanic_edit'),
    url(r'^mechanic/(?P<mechanic_id>[0-9]+)/(?P<status>[01])$', views.mechanic_update_status, name='mechanic_update_status'),
    
    url(r'^issue/$', views.issue_list, name='issue_list'),
    url(r'^issue/(?P<issue_id>[0-9]+)/$', views.issue_detail, name='issue_detail'),
    url(r'^issue/(?P<issue_id>[0-9]+)/edit$', views.issue_edit, name='issue_edit'),
    url(r'^issue/add/$', views.issue_add, name='issue_add'),
    url(r'^issue/add/(?P<bus_id>[0-9]+)/$', views.issue_add, name='issue_add'),
    url(r'^issue/fixed$', views.issue_fixed, name='issue_fixed'),
    url(r'^issue/delete/(?P<issue_id>[0-9]+)/$', views.issue_delete, name='issue_delete'),
    
    url(r'^issue/print/$', views.issue_print, name='issue_print'),
]

nvbc/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^busbarn/', include('busbarn.urls',namespace="busbarn")),
    url(r'^admin/', admin.site.urls),
]

busbarn/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.timezone import now
from datetime import datetime

# Create your models here.

class Vehicle(models.Model):
    VEHICLE_CLASSES = (
        ('Long Bus', 'Long Bus'),
        ('Medium Bus', 'Medium Bus'),
        ('Short Bus', 'Short Bus'),
        ('Shuttle', 'Shuttle'),
        ('Trolly', 'Trolly'),
        ('Van' , 'Van'),
        ('Truck', 'Truck'),
        ('Car', 'Car'),
    )
    vin_number = models.CharField(max_length=17, unique=True, default=None)
    license_plate = models.CharField(max_length=10)
    vehicle_class = models.CharField(max_length=10, choices=VEHICLE_CLASSES)
    vehicle_name = models.CharField(max_length=30, default='default')
    remarks = models.TextField(blank=True)
    retired = models.BooleanField(default=False)
    
    def __str__(self):
        return self.vehicle_name

    class Meta:
        ordering = ['vehicle_name']

class Mechanic(models.Model):
    name = models.CharField(max_length=30)
    phone = models.CharField(max_length=12, blank=True, null=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name
    
class Issue(models.Model):
    SEVERITY_OPTIONS = (
        ('Urgent', 'Urgent'),
        ('OOS', 'OOS'),
    )
    REASONS = (
        ('Driver Write-up', 'Driver Write-up'),
        ('PM Work', 'PM Work'),
        ('Other Scheduled', 'Other Scheduled'),
    )
    REPAIR_CODES = (
        ('Repaired or Tightened', 'Repaired or tightened'),
        ('Replaced', 'Replaced'),
        ('Checked, found OK', 'Checked, found OK'),
    )
    
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE) # so... don't delete
    date_noted = models.DateTimeField('date noted')
    severity = models.CharField(max_length=12, choices=SEVERITY_OPTIONS)
    description = models.CharField(max_length=100)

    # mechanic = models.CharField(max_length=30, blank=True)
    mechanic = models.ForeignKey(
        Mechanic,
        blank=True, null=True, #Allows field to be blank in the form and database
        on_delete=models.PROTECT, #Preserves the record; prevents deleting mechanics with records
        limit_choices_to={'active': True} #Only shows active mechanics in the form
    ) 

    
    date_completed = models.DateTimeField('date completed', blank=True, null=True)
    remarks = models.TextField(blank=True)
    reason = models.CharField(max_length=21, choices=REASONS, default="Other scheduled")
    repair = models.CharField(max_length=21, choices=REPAIR_CODES, blank=True)
    last_updated = models.DateTimeField('Last updated', default=now, blank=True)
    deleted = models.BooleanField(default=False)
    
    def __str__(self):
        return self.description

    def println(self):
        line = self.vehicle.vehicle_name + " \t" + self.description + "\t"
        line = line + self.mechanic
        return line

busbarn/forms.py
from django import forms
from django.forms import ModelForm
from .models import Vehicle, Issue, Mechanic  ### is this needed?

class IssueForm(ModelForm):
    class Meta:
        model = Issue
        fields = ('vehicle', 'severity', 'description', 'mechanic',
                  'reason', 'repair', 'remarks', 'date_noted')


        def __init__(self, *args, **kwargs):
            super(IssueForm, self).__init__(*args, **kwargs)
            self.fields['date_completed'].required = False
            self.fields['repair'].required=False
            self.fields['remarks'].required=False

class MechanicForm(ModelForm):
    class Meta:
        model = Mechanic
        fields = ('name','phone','active')

class VehicleForm(ModelForm):
    class Meta:
        model = Vehicle
        fields = ('vehicle_name', 'license_plate', 'vehicle_class',
                  'vin_number', 'remarks', 'retired')

busbarn/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.timezone import now
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
import datetime


# Create your views here.
from .models import Vehicle, Issue, Mechanic
from .forms import IssueForm, MechanicForm, VehicleForm

def index(request):
    return HttpResponseRedirect(reverse('busbarn:issue_list'))

def vehicle_list(request):
    vehicle_list = Vehicle.objects.filter(retired=False)
    context = {'vehicle_list': vehicle_list}
    return render(request, 'busbarn/vehicle_list.html', context)

def vehicle_detail(request, vehicle_id):
    # For this we need the vehicle detail and all associated 
    vehicle = get_object_or_404(Vehicle, pk=vehicle_id)
    issues = Issue.objects.filter(vehicle_id=vehicle_id)
    return render(request, 'busbarn/vehicle_detail.html', {'vehicle': vehicle, 'issues': issues })

def vehicle_add(request):
    if request.method == "POST":
        form = VehicleForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('busbarn:vehicle_list'))
    else:
        form = VehicleForm()
        return render(request, 'busbarn/vehicle_add.html', {'form': form})

def vehicle_edit(request, vehicle_id):
    instance = get_object_or_404(Vehicle, id=vehicle_id)
    form = VehicleForm(request.POST or None, instance=instance)
    if form.is_valid():
        form.save()
        instance.save()
        return HttpResponseRedirect(reverse('busbarn:vehicle_list'))
    return render(request, 'busbarn/vehicle_edit.html', {'form': form, 'vehicle': instance})

def mechanic_list(request):
    mechanic_list = Mechanic.objects.filter(active=True).order_by('name')
    #mechanic_list = Mechanic.objects.order_by('name')
    context = {'mechanic_list': mechanic_list}
    return render(request, 'busbarn/mechanic_list.html', context)

def mechanic_add(request):
    # TODO: implement using issue add as a template
    if request.method == "POST":
        form = MechanicForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('busbarn:mechanic_list'))
    else:
        form = MechanicForm()
        return render(request, 'busbarn/mechanic_add.html', {'form': form})

def mechanic_update_status(request, mechanic_id, status):
    mechanic = get_object_or_404(Mechanic, id=mechanic_id)
    if status=="1":
        print("activating")
        mechanic.active = True
    else:
        print("deactivating")
        mechanic.active = False
    mechanic.save()
    return HttpResponseRedirect(reverse('busbarn:mechanic_list'))

def mechanic_edit(request, mechanic_id):
    instance = get_object_or_404(Mechanic, id=mechanic_id)
    form = MechanicForm(request.POST or None, instance=instance)
    if form.is_valid():
        form.save()
        instance.save()
        return HttpResponseRedirect(reverse('busbarn:mechanic_list'))
    return render(request, 'busbarn/mechanic_edit.html', {'form': form, 'mechanic': instance})

def issue_list(request):
    issue_list = Issue.objects.filter(date_completed__isnull=True).filter(deleted=False).order_by('vehicle__vehicle_name')
    context = {'issue_list': issue_list}
    return render(request, 'busbarn/issue_list.html', context)
def issue_fixed(request):
    issue_list = Issue.objects.filter(date_completed__isnull=False).order_by('vehicle__vehicle_name')
    context = {'issue_list': issue_list}
    return render(request, 'busbarn/issue_fixed.html', context)


def issue_detail(request, issue_id):
    issue = Issue.objects.get(pk=issue_id)
    return render(request, 'busbarn/issue_detail.html', {'issue': issue})

def issue_edit(request, issue_id):
    instance = get_object_or_404(Issue, id=issue_id)
    form = IssueForm(request.POST or None, instance=instance)
    if form.is_valid():
        form.save()
        form.cleaned_data['last_updated'] = now()
        if not form.cleaned_data['repair'] == "":
            instance.date_completed = now()
            instance.save()
        return HttpResponseRedirect(reverse('busbarn:issue_list'))
    return render(request, 'busbarn/issue_edit.html', {'form': form, 'issue': instance})

def issue_add(request, bus_id=None):
    if request.method == "POST":
        form = IssueForm(request.POST)
        if form.is_valid():
            form.cleaned_data['date_noted'] = now()
            #form.cleaned_data['last_updated'] = now()
            form.save()
            return HttpResponseRedirect(reverse('busbarn:issue_list'))
    else:
        if bus_id:
            form = IssueForm({'date_noted': now(), 'vehicle': bus_id})
        else:
            form = IssueForm({'date_noted': now()})
        #form.fields['date_noted'].disabled = True
        return render(request, 'busbarn/issue_add.html', {'form': form})

def issue_delete(request, issue_id):
    issue = get_object_or_404(Issue, id=issue_id)
    issue.last_updated = now()
    issue.deleted = True
    issue.save()
    return HttpResponseRedirect(reverse("busbarn:issue_list"))
    
def issue_print(request):
    issue_list = Issue.objects.filter(date_completed__isnull=True).filter(deleted=False).order_by('vehicle__vehicle_name')

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="printout.pdf"'
    now = datetime.datetime.now()
    
    p = canvas.Canvas(response, bottomup=0, pagesize=letter)

    vertValue = 40
    p.drawString(30, vertValue, "Vehicle")
    p.drawString(85, vertValue, "Priority")
    p.drawString(130, vertValue, "Reason")
    p.drawString(220, vertValue, "Problem")
    #add date that the report was generated
    p.drawString(420, vertValue, now.strftime("Report Generated %m/%d/%Y"))
    vertValue=70

    page_entry=1
    page_number=1
    for issue in issue_list:
        if (page_entry==36):
            p.drawString(550, vertValue, "page {0}".format(page_number))
            page_entry=1
            page_number+=1
            p.showPage()
            vertValue=40
            p.drawString(30, vertValue, "Vehicle")
            p.drawString(85, vertValue, "Priority")
            p.drawString(130, vertValue, "Reason")
            p.drawString(220, vertValue, "Problem")
            #add date that the report was generated
            p.drawString(420, vertValue, now.strftime("Report Generated %m/%d/%Y"))
            vertValue=70

        p.drawString(30, vertValue, issue.vehicle.vehicle_name)
        p.drawString(85, vertValue, issue.severity)
        p.drawString(130, vertValue, issue.reason)
        p.drawString(220, vertValue, issue.description)
        vertValue = vertValue + 20
        page_entry+=1

    p.drawString(550, 770, "page {0}".format(page_number))
    p.showPage()
    p.save()
    return response

busbarn/templates/busbarn/base.html
<html>
  <head>
    {% load bootstrap4 %}

    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="align-left" style="margin-left: auto; margin-right: auto;">
	<ul class="nav navbar-nav">
	  <li class="nav-item"><a class="nav-link" href="{% url 'vehicles:vehicle_list' %}">Vehicle List</a></li>
	  <li class="nav-item"><a class="nav-link" href="{% url 'vehicles:issue_list' %}">Issue List</a></li>
	  <li class="nav-item"><a class="nav-link" href="{% url 'vehicles:issue_fixed' %}">Completed Jobs</a></li>
	  <li class="nav-item"><a class="nav-link" href="{% url 'vehicles:mechanic_list' %}">Mechanics</a></li>
	</ul>
      </div>
    </nav>
    
    {% bootstrap_messages %}
    <div style="width:80%; margin-left: auto; margin-right: auto;">
    {% block content %}
    {% endblock %}
    </div>
  </body>
</html>

busbarn/templates/busbarn/issue_add.html
{% extends "busbarn/base.html" %}
{% load bootstrap4 %}

{% block content %}

<h1>Creating new Issue</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'vehicles:issue_add' %}" method="post">
  {% csrf_token %}
  <table class="table">
    {{ form.as_table }}
  </table>

  
  {% buttons %}
  <input type="submit" value="Create" />
  {% endbuttons %}
</form>

{% endblock %}

busbarn/templates/busbarn/issue_detail.html
{% extends "busbarn/base.html" %}

{% load bootstrap4 %}

{% block content %}
<h1>Issue {{ issue.id }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<table class="table">
  <tr><th>Description</th><td>{{ issue.description }}</td></tr>
  <tr><th>Vehicle</th><td>{{ issue.vehicle.vehicle_name }}</td></tr>
  <tr><th>Date Noted</th><td>{{ issue.date_noted }}</td></tr>
  <tr><th>Severity</th><td>{{ issue.severity }}</td></tr>
  <tr><th>Mechanic Assigned</th><td>{{ issue.mechanic }}</td></tr>
  <tr><th>Date Completed</th><td>{{ issue.date_completed }}</td></tr>
  <tr><th>Reason</th><td>{{ issue.reason }}</td></tr>
  <tr><th>Repair</th><td>{{ issue.repair }}</td></tr>
  <tr><th>Notes</th><td>{{ issue.notes }}</td></tr>
</table>

<a class="btn btn-success" href="{% url 'vehicles:issue_edit' issue.id %}">Edit Issue</a>

{% endblock %}

busbarn/templates/busbarn/issue_edit.html
{% extends "busbarn/base.html" %}

{% block content %}

<h1>Editing Issue {{ issue.id }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'vehicles:issue_edit' issue.id %}" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
<input type="submit" value="Update" />
</form>

<p><a href="{% url 'vehicles:issue_delete' issue.id %}" class="btn btn-danger">Delete Write-up</a>
{% endblock %}

busbarn/templates/busbarn/issue_fixed.html
{% extends "busbarn/base.html" %}

{% load bootstrap4 %}

{% block content %}
<h1>Completed Jobs</h1>

{% if issue_list %}
<table class="table">
  <tr>
    <th>Vehicle</th>
    <th>Description</th>
    <th>Start Date</th>
    <th>Severity</th>
    <th>Mechanic</th>
    <th>Reason</th>
    <th></th>
  </tr>
  
  {% for issue in issue_list %}
  <tr>
    <td><a href="{% url 'vehicles:vehicle_detail' issue.vehicle.id %}">{{ issue.vehicle.vehicle_name }}</a></td>
    <td>{{ issue.description }}</td>
    <td>{{ issue.date_noted|date:'m/d/Y' }}</td>
    <td>{{ issue.severity }}</td>
    <td>{{ issue.mechanic }}</td>
    <td>{{ issue.reason }}</td>
    <td><a href="{% url 'vehicles:issue_detail' issue.id %}" class="btn btn-success">View</a></td>
    <td><a href="{% url 'vehicles:issue_edit' issue.id %}" class="btn btn-success">Edit</a></td>
  </tr>
    
  {% endfor %}
</table>

{% else %}
<p> There are no outstanding issues at this time. </p>
{% endif %}

<p><a href="{% url 'vehicles:issue_add' %}" class="btn btn-success">Create Write Up</a>

<p><a href="{% url 'vehicles:issue_print' %}" class="btn btn-success">Print List</a>

{% endblock %}

busbarn/templates/busbarn/issue_list.html
{% extends "busbarn/base.html" %}

{% load bootstrap4 %}

{% block content %}
<h1>Active Issues</h1>

{% if issue_list %}
<table class="table">
  <tr>
    <th>Vehicle</th>
    <th>Description</th>
    <th>Start Date</th>
    <th>Severity</th>
    <th>Mechanic</th>
    <th>Reason</th>
    <th></th>
  </tr>
  
  {% for issue in issue_list %}
  <tr>
    <td><a href="{% url 'vehicles:vehicle_detail' issue.vehicle.id %}">{{ issue.vehicle.vehicle_name }}</a></td>
    <td>{{ issue.description }}</td>
    <td>{{ issue.date_noted|date:'m/d/Y' }}</td>
    <td>{{ issue.severity }}</td>
    <td>{{ issue.mechanic|default_if_none:"" }}</td>
    <td>{{ issue.reason }}</td>
    <td><a href="{% url 'vehicles:issue_detail' issue.id %}" >View</a></td>
    <td><a href="{% url 'vehicles:issue_edit' issue.id %}" >Edit</a></td>
  </tr>
    
  {% endfor %}
</table>

{% else %}
<p> There are no outstanding issues at this time. </p>
{% endif %}

<p><a href="{% url 'vehicles:issue_add' %}" class="btn btn-success">Create Write Up</a>

<p><a href="{% url 'vehicles:issue_print' %}" class="btn btn-success">Print List</a>

{% endblock %}

busbarn/templates/busbarn/mechanic_add.html
{% extends "busbarn/base.html" %}
{% load bootstrap4 %}

{% block content %}

<h1>Add New Mechanic</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'vehicles:mechanic_add' %}" method="post">
  {% csrf_token %}
  <table class="table">
    {{ form.as_table }}
  </table>

  
  {% buttons %}
  <input type="submit" value="Create" />
  {% endbuttons %}
</form>

{% endblock %}

busbarn/templates/busbarn/mechanic_edit.html
{% extends "busbarn/base.html" %}

{% block content %}

<h1>Editing Issue {{ issue.id }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'vehicles:mechanic_edit' mechanic.id %}" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
<input type="submit" value="Update" />
</form>

{% endblock %}

busbarn/templates/busbarn/mechanic_list.html
{% extends "busbarn/base.html" %}

{% load bootstrap4 %}

{% block content %}
<h1>Mechanics</h1>

{% if mechanic_list %}
<table class="table">
  <tr>
    <th>Name</th>
    <th>Phone #</th>
    <th>Status</th>
    <th></th>
    <th></th>
  </tr>

  {% for mechanic in mechanic_list %}
  <tr>
    <td>{{ mechanic.name }}</td>
    <td>{% if mechanic.phone %} {{mechanic.phone}} {% else %} &nbsp; {% endif %}</td>
    {% if mechanic.active %}
    <td>Active</td>
    <td><a href="{% url 'vehicles:mechanic_update_status' mechanic.id 0 %}">Deactivate</a></td>
    {% else %}
    <td>Inactive</td>
    <td><a href="{% url 'vehicles:mechanic_update_status' mechanic.id 1 %}">Activate</a></td>
    {% endif %}
    
    <td><a href="{% url 'vehicles:mechanic_edit' mechanic.id %}" >Edit</a></td>

  </tr>
  {% endfor %}
</table>

{% else %}
<p> You have no mechanics registered at this time.</p>
{% endif %}

<p><a href="{% url 'vehicles:mechanic_add' %}" class="btn btn-success">Add Mechanic</a>

{% endblock %}

busbarn/templates/busbarn/vehicle_add.html
{% extends "busbarn/base.html" %}
{% load bootstrap4 %}

{% block content %}

<h1>Add New Mechanic</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'vehicles:vehicle_add' %}" method="post">
  {% csrf_token %}
  <table class="table">
    {{ form.as_table }}
  </table>

  
  {% buttons %}
  <input type="submit" value="Create" />
  {% endbuttons %}
</form>

{% endblock %}

busbarn/templates/busbarn/vehicle_detail.html
{% extends "busbarn/base.html" %}
{% load bootstrap4 %}

{% block content %}

<h1>{{ vehicle.vehicle_name }}</h1>

<p>Vin: {{ vehicle.vin_number }}</p>
<p>Class: {{ vehicle.vehicle_class }}</p>
<p>License: {{ vehicle.license_plate }}</p>
<p>Notes: {{ vehicle.notes }}</p>

{% if issues %}
<h2>Issues:</h2>
<table class="table">
  <tr><th>Description</th>
  <th>Start Date</th>
  <th>Severity</th>
  <th>Mechanic</th>
  <th>Reason</th></tr>

  {% for issue in issues %}
  <tr>
    <td><a href="{% url 'vehicles:issue_detail' issue.id %}">{{ issue.description }}</a></td>
    <td>{{ issue.date_noted }}</td>
    <td>{{ issue.severity }}</td>
    <td>{{ issue.mechanic }}</td>
    <td>{{ issue.reason }}</td>
  </tr>
  {% endfor %}
</table>
{% else %}
<p>No current issues</p>
{% endif %}


<a href="{% url 'vehicles:issue_add' vehicle.id %}">Add Issue</a>
{% endblock %}

busbarn/templates/busbarn/vehicle_edit.html
{% extends "busbarn/base.html" %}

{% block content %}

<h1>Editing Vehicle {{ vehicle.id }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'vehicles:vehicle_edit' vehicle.id %}" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
<input type="submit" value="Update" />
</form>

{% endblock %}

busbarn/templates/busbarn/vehicle_list.html
{% extends "busbarn/base.html" %}

{% load bootstrap4 %}

{% block content %}
{% if vehicle_list %}
<table class="table">
  <tr>
    <th>Vehicle Name</th>
    <th>Vin Number</th>
    <th>License Plate</th>
    <th>Vehicle Class</th>
    <th></th>
    <th></th>
  </tr>
  {% for vehicle in vehicle_list %}
  <tr>
    <td>{{ vehicle.vehicle_name }}</td>
    <td>{{ vehicle.vin_number }}</td>
    <td>{{ vehicle.license_plate }}</td>
    <td>{{ vehicle.vehicle_class }}</td>
    <td><a href="{% url 'vehicles:vehicle_edit' vehicle.id %}" class="btn">Edit</a></td>
    <td><a href="{% url 'vehicles:vehicle_detail' vehicle.id %}" class="btn">View</a></td>
  </tr>
  {% endfor %}
</table>
{% else %}
<p> You have no vehicles registered for this application at this time. </p>
{% endif %}

<p><a href="{% url 'vehicles:vehicle_add' %}" class="btn btn-success">Add Vehicle</a>

{% endblock %}